// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalentMatch.Infrastructure.Persistence;

#nullable disable

namespace TalentMatch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("TalentMatch.Domain.Entities.AggregatedResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ConsolidatedRationale")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RationaleText");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("FinalDecision");

                    b.Property<double>("FinalScore")
                        .HasColumnType("REAL");

                    b.Property<string>("FinalSubScoresJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MergedImprovementTipsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RecommendationsText");

                    b.Property<double>("Variance")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("AggregatedResults");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.Application", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CandidateRef")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalDecision")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<double?>("FinalScore")
                        .HasColumnType("REAL");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TestRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Variance")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("TestRunId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.ApplicationDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSha256")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SizeBytes");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MimeType");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadTimestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("UploadedAt");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ApplicationDocuments");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasFilter("[Status] = 'active'");

                    b.ToTable("Departments", t =>
                        {
                            t.HasCheckConstraint("CK_Departments_Status", "Status IN ('active', 'retired')");
                        });
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.DepartmentMembership", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("DepartmentId", "OrganizationId");

                    b.HasIndex("UserId", "DepartmentId")
                        .IsUnique()
                        .HasFilter("[Status] = 'active'");

                    b.ToTable("DepartmentMemberships", t =>
                        {
                            t.HasCheckConstraint("CK_DepartmentMemberships_Status", "(Status = 'active' AND RevokedAt IS NULL) OR (Status = 'revoked' AND RevokedAt IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.DocumentBlob", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId");

                    b.ToTable("DocumentBlobs");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.ExtractionArtifact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("REAL")
                        .HasColumnName("Confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalisedText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Markdown");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("ExtractionArtifacts");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.FailureQueueItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FailureQueueItems");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.Job", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentConfigVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "OrganizationId");

                    b.HasIndex("OrganizationId", "DepartmentId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.JobConfigVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AggregationStrategy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesiredCriteriaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("LonglistThreshold")
                        .HasColumnType("REAL");

                    b.Property<string>("MustHaveCriteriaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MustHavesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MustHavesJson");

                    b.Property<string>("RawExtractionResponse")
                        .HasColumnType("TEXT");

                    b.Property<string>("RubricApprovalStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RubricJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RubricSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RunsPerApplication")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RunsPerApplication");

                    b.Property<int>("ScoringRunCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ShortlistThreshold")
                        .HasColumnType("REAL");

                    b.Property<double>("VarianceThreshold")
                        .HasColumnType("REAL");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobConfigVersions");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.ManualReviewData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedFinalScore")
                        .HasColumnType("REAL");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuditTrailJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HumanEdited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OverallComment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RubricScoresJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("ManualReviews");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Status] = 'active'");

                    b.ToTable("Organizations", t =>
                        {
                            t.HasCheckConstraint("CK_Organizations_Status", "Status IN ('active', 'retired')");
                        });
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.OrganizationMembership", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId", "OrganizationId")
                        .IsUnique()
                        .HasFilter("[Status] = 'active'");

                    b.ToTable("OrganizationMemberships", t =>
                        {
                            t.HasCheckConstraint("CK_OrganizationMemberships_Status", "(Status = 'active' AND RevokedAt IS NULL) OR (Status = 'revoked' AND RevokedAt IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.PasswordResetRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetRequests");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.ProcessingEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Action");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DetailsJson");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("ProcessingEvents");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.PromptTestRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("PromptId");

                    b.ToTable("PromptTestRuns");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.RoleAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleGroupMappingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("active");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserObjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleGroupMappingId");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserObjectId", "RoleGroupMappingId")
                        .IsUnique()
                        .HasFilter("[Status] = 'active' AND [RoleGroupMappingId] IS NOT NULL");

                    b.HasIndex("TenantId", "UserObjectId", "Source", "Role", "OrganizationId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("RoleAssignments", t =>
                        {
                            t.HasCheckConstraint("CK_RoleAssignments_Status", "(Status = 'active' AND RevokedAt IS NULL) OR (Status = 'revoked' AND RevokedAt IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.RoleGroupMapping", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GroupObjectId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "GroupObjectId")
                        .IsUnique();

                    b.ToTable("RoleGroupMappings", t =>
                        {
                            t.HasCheckConstraint("CK_RoleGroupMappings_Scope", "(Role = 'admin' AND OrganizationId IS NULL AND DepartmentId IS NULL) OR (Role = 'organization_admin' AND OrganizationId IS NOT NULL AND DepartmentId IS NULL) OR (Role = 'recruiter' AND OrganizationId IS NOT NULL AND DepartmentId IS NOT NULL) OR (Role = 'business_panel' AND OrganizationId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.ScoringBatch", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("BatchId");

                    b.Property<string>("ApplicationIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPolledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LeasedUntil")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextPollAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PollUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("RunCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("IX_ScoringBatches_JobId");

                    b.HasIndex("SubmissionId")
                        .IsUnique()
                        .HasDatabaseName("UX_ScoringBatches_SubmissionId")
                        .HasFilter("[SubmissionId] IS NOT NULL");

                    b.HasIndex("Status", "NextPollAt")
                        .HasDatabaseName("IX_ScoringBatches_Status_NextPollAt");

                    b.ToTable("ScoringBatches", (string)null);
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.ScoringJobProgress", b =>
                {
                    b.Property<string>("JobId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<int>("AppsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppsFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatchesCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatchesFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatchesPending")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatchesSubmitted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CancelRequested")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalApps")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("JobId");

                    b.ToTable("ScoringJobProgress", (string)null);
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.ScoringPrompt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Comments")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenerationMetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Status");

                    b.ToTable("ScoringPrompts");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.ScoringRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiModelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ModelDeploymentId");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryScoresJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SubScoresJson");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceCitationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImprovementTipsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ImprovementRecsJson");

                    b.Property<string>("MustHaveEvaluationJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MustHaveResultJson");

                    b.Property<double?>("ParserConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ParserWarningsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PromptVersionId");

                    b.Property<string>("RawParsedResponseJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawResponseText")
                        .HasColumnType("TEXT");

                    b.Property<int>("RunIndex")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalScore")
                        .HasColumnType("REAL")
                        .HasColumnName("OverallScore");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ScoringRuns");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthenticationProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("simple");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntraObjectId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntraTenantId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PasswordResetRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("EntraTenantId", "EntraObjectId")
                        .IsUnique()
                        .HasFilter("[AuthenticationProvider] = 'entra'");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_IdentityProvider", "(AuthenticationProvider = 'simple' AND PasswordHash IS NOT NULL AND EntraTenantId IS NULL AND EntraObjectId IS NULL) OR (AuthenticationProvider = 'entra' AND PasswordHash IS NULL AND EntraTenantId IS NOT NULL AND EntraObjectId IS NOT NULL AND PasswordResetRequired = 0)");
                        });
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.AggregatedResult", b =>
                {
                    b.HasOne("TalentMatch.Domain.Entities.Application", "Application")
                        .WithOne("AggregatedResult")
                        .HasForeignKey("TalentMatch.Domain.Entities.AggregatedResult", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.Application", b =>
                {
                    b.HasOne("TalentMatch.Domain.Entities.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.ApplicationDocument", b =>
                {
                    b.HasOne("TalentMatch.Domain.Entities.Application", "Application")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.Department", b =>
                {
                    b.HasOne("TalentMatch.Domain.Entities.Organization", "Organization")
                        .WithMany("Departments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.DepartmentMembership", b =>
                {
                    b.HasOne("TalentMatch.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalentMatch.Domain.Entities.User", "User")
                        .WithMany("DepartmentMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TalentMatch.Domain.Entities.Department", "Department")
                        .WithMany("Memberships")
                        .HasForeignKey("DepartmentId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.DocumentBlob", b =>
                {
                    b.HasOne("TalentMatch.Domain.Entities.ApplicationDocument", null)
                        .WithOne()
                        .HasForeignKey("TalentMatch.Domain.Entities.DocumentBlob", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.ExtractionArtifact", b =>
                {
                    b.HasOne("TalentMatch.Domain.Entities.Application", "Application")
                        .WithOne("Extraction")
                        .HasForeignKey("TalentMatch.Domain.Entities.ExtractionArtifact", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.Job", b =>
                {
                    b.HasOne("TalentMatch.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TalentMatch.Domain.Entities.Department", "DepartmentEntity")
                        .WithMany()
                        .HasForeignKey("DepartmentId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DepartmentEntity");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.JobConfigVersion", b =>
                {
                    b.HasOne("TalentMatch.Domain.Entities.Job", "Job")
                        .WithMany("ConfigVersions")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.ManualReviewData", b =>
                {
                    b.HasOne("TalentMatch.Domain.Entities.Application", "Application")
                        .WithOne("ManualReview")
                        .HasForeignKey("TalentMatch.Domain.Entities.ManualReviewData", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.OrganizationMembership", b =>
                {
                    b.HasOne("TalentMatch.Domain.Entities.Organization", "Organization")
                        .WithMany("Memberships")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalentMatch.Domain.Entities.User", "User")
                        .WithMany("OrganizationMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.PromptTestRun", b =>
                {
                    b.HasOne("TalentMatch.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TalentMatch.Domain.Entities.ScoringPrompt", "Prompt")
                        .WithMany("TestRuns")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.RoleAssignment", b =>
                {
                    b.HasOne("TalentMatch.Domain.Entities.RoleGroupMapping", "RoleGroupMapping")
                        .WithMany()
                        .HasForeignKey("RoleGroupMappingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TalentMatch.Domain.Entities.User", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleGroupMapping");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.ScoringPrompt", b =>
                {
                    b.HasOne("TalentMatch.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.ScoringRun", b =>
                {
                    b.HasOne("TalentMatch.Domain.Entities.Application", "Application")
                        .WithMany("ScoringRuns")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.Application", b =>
                {
                    b.Navigation("AggregatedResult");

                    b.Navigation("Documents");

                    b.Navigation("Extraction");

                    b.Navigation("ManualReview");

                    b.Navigation("ScoringRuns");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.Department", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.Job", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("ConfigVersions");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.ScoringPrompt", b =>
                {
                    b.Navigation("TestRuns");
                });

            modelBuilder.Entity("TalentMatch.Domain.Entities.User", b =>
                {
                    b.Navigation("DepartmentMemberships");

                    b.Navigation("OrganizationMemberships");

                    b.Navigation("RoleAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
